baseurl = "https://sgxu79.github.io/"
title = "Steven Xu"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "sgxu79.github.io"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Steven Xu"
    info = "Third year statistics Ph.D. student @ NCSU"
    description = "Steven Xu's personal website"
    keywords = "personal"
    avatarurl = "images/avatar.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

#    footercontent = "Enter a text here."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://linkedin.com/in/sgxu79"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab fa-2x"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
#[[params.social]]
#    name = "Twitter"
#    icon = "fab fa-twitter fa-2x"
#    weight = 3
#    url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about/"
[[menu.main]]
    name = "CV"
    weight = 2
    url  = "CV/"
[[menu.main]]
    name = "Project"
    weight = 3
    url  = "Project/"
